spring:
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    username: igor
    password: admin
#    url: jdbc:h2:file:C:\Users\igorl\IdeaProjects\practice\db\practice
    url: jdbc:h2:mem:practiceDB
#    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true