spring:
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    username: igor
    password: admin
    url: jdbc:h2:file:~/db/practice
  h2:
    console:
      enabled: true